### ISSUE TITLE
Wrong admin area, and wrong password

### ISSUE THREAD

**Issue by BoniWPy** [yvsser1/ecommerce-website#1]
the right admin panel area is /admin_area not an /admin_panel
and the password is wrong

**Comment by farrukhahmed4220** [comment]
Did you solved this problem?

**Comment by farrukhahmed4220** [comment]
Same problem, I have also inserted record manually into admin table... and try to login but it still showing the same...

**Comment by BoniWPy** [comment]
> Same problem, I have also inserted record manually into admin table... and try to login but it still showing the same...

no i dont, hehe

**Comment by BoniWPy** [comment]
RIP for develope.

**Comment by yvsser1** [comment]
yes my bad i fixed it, the admin panel area is /admin_area not an /admin_panel
and about the login informations you can set yours in the database
Thanks !
