### ISSUE TITLE
> sorry for replying late but this project is old anyway here is the infos :

### ISSUE THREAD

**Issue by Uzbekyt** [yvsser1/ecommerce-website#10]
> sorry for replying late but this project is old anyway here is the infos :
> 
Thank you for amazing website. There is one issue I found. When registering new customer, it is asking captcha verification. But captcha varification is not working. I cannot even click on it. 
I would be glad if you could tell me something about it ( any tip to fix, or remove captcha).

_Originally posted by @Uzbekyt in https://github.com/yvsser1/ecommerce-website/issues/6#issuecomment-730567476_

**Comment by yvsser1** [comment]
there is a code in customer_register.php
 `<div class="g-recaptcha" data-sitekey="your_site_key"></div>`
you need to update "your_site_key" by going to google recaptcha and getting your own key or just remove the whole captcha code

**Comment by Uzbekyt** [comment]
> there is a code in customer_register.php
> `<div class="g-recaptcha" data-sitekey="your_site_key"></div>`
> you need to update "your_site_key" by going to google recaptcha and getting your own key or just remove the whole captcha code

Thank you very much for your accountability for your work. I have already found that. Thank you.
