### ISSUE TITLE
Admin Login Credentials

### ISSUE THREAD

**Issue by yendiscart** [yvsser1/ecommerce-website#6]
Please provide me with Admin Login Credentials. Thanks.

**Comment by arthur1997-wq** [comment]
please can you provide me with Admin Login Credentials if you want . Thanks

**Comment by yvsser1** [comment]
sorry for replying late but this project is old anyway here is the infos : 

user information:
email:ave@user.com
password:123

admin information:
email:ave@user.com
password:123

**Comment by Uzbekyt** [comment]
> sorry for replying late but this project is old anyway here is the infos :
> 
Thank you for amazing website. There is one issue I found. When registering new customer, it is asking captcha verification. But captcha varification is not working. I cannot even click on it. 
I would be glad if you could tell me something about it ( any tip to fix, or remove captcha).
